import os
from dotenv import load_dotenv

load_dotenv()

BITRIX24_WEBHOOK = os.getenv('BITRIX24_WEBHOOK')
BITRIX24_DOMAIN = os.getenv('BITRIX24_DOMAIN', 'online-kassa.bitrix24.ru')
BITRIX24_CLIENT_ID = os.getenv('BITRIX24_CLIENT_ID')
BITRIX24_CLIENT_SECRET = os.getenv('BITRIX24_CLIENT_SECRET')
BITRIX24_ACCESS_TOKEN = os.getenv('BITRIX24_ACCESS_TOKEN')
BITRIX24_REFRESH_TOKEN = os.getenv('BITRIX24_REFRESH_TOKEN')
BITRIX24_MAX_ATTEMPTS = int(os.getenv('BITRIX24_MAX_ATTEMPTS', '5'))
BITRIX24_TIMEOUT_SEC = float(os.getenv('BITRIX24_TIMEOUT_SEC', '30'))
BITRIX24_BACKOFF_BASE_SEC = float(os.getenv('BITRIX24_BACKOFF_BASE_SEC', '0.6'))
BITRIX24_BACKOFF_MAX_SEC = float(os.getenv('BITRIX24_BACKOFF_MAX_SEC', '20'))

BITNEWTON_ASR_URL = os.getenv('BITNEWTON_ASR_URL', 'https://bit-asr.1bitai.ru')
BITNEWTON_TOKEN = os.getenv('BITNEWTON_TOKEN')

VIBECODE_API_KEY = os.getenv('VIBECODE_API_KEY')
VIBECODE_TIMEOUT_SEC = float(os.getenv('VIBECODE_TIMEOUT_SEC', '30'))
VIBECODE_MAX_ATTEMPTS = int(os.getenv('VIBECODE_MAX_ATTEMPTS', '3'))

REPORTS_DIR = 'reports'
os.makedirs(REPORTS_DIR, exist_ok=True)
