from __future__ import annotations

RU_COLUMNS: dict[str, str] = {
    "deal_id": "ID сделки",
    "deal_url": "Ссылка на сделку",
    "stage_id": "Стадия",
    "stage_name": "Стадия",
    "stage_history_event_id": "ID события стадии",
    "stage_history_event_type": "Тип события стадии",
    "stage_history_created_at": "Дата смены стадии",
    "stage_history_count": "Кол-во переходов по стадиям",
    "stage_history_path": "Маршрут стадий",
    "stage_duration_minutes": "Время до следующей стадии, мин.",
    "stage_duration_hours": "Время до следующей стадии, ч.",
    "stage_is_current": "Текущая стадия",
    "stage_last_change_at": "Последняя смена стадии",
    "stage_current_age_minutes": "Время в текущей стадии, мин.",
    "stage_current_age_days": "Время в текущей стадии, дн.",
    "stage_warning_threshold": "Порог предупреждения по стадии",
    "stage_critical_threshold": "Порог тревоги по стадии",
    "stage_current_age_status": "Статус срока в стадии",
    "deal_total_work_minutes": "Общее время в работе, мин.",
    "deal_total_work_days": "Общее время в работе, дн.",
    "deal_total_work_warning_threshold": "Порог предупреждения по сделке",
    "deal_total_work_critical_threshold": "Порог тревоги по сделке",
    "deal_total_work_status": "Статус общего срока сделки",
    "stage_return_count": "Возвраты на предыдущие стадии",
    "stage_reached_final": "Достигнута финальная стадия",
    "stage_movement_risk": "Риск движения по воронке",
    "stage_movement_recommendation": "Рекомендация по движению сделки",
    "stage_deals_total": "Всего сделок",
    "stage_deals_passed": "Сделок прошло стадию",
    "stage_sr": "SR стадии, %",
    "stage_order": "Порядок стадии",
    "manager_id": "ID менеджера",
    "manager_name": "Менеджер",
    "kpi_profile": "Профиль KPI",
    "kpi_profile_ru": "Профиль KPI",
    "kpi_explanation": "Расшифровка KPI",
    "kpi_version": "Версия KPI",
    "kpi_profile_cmp": "Профиль KPI сравнения",
    "kpi_version_cmp": "Версия KPI сравнения",
    "activity_id": "ID активности",
    "origin_id": "ID звонка Bitrix",
    "subject": "Тема звонка",
    "duration_minutes": "Длительность звонка, мин.",
    "disk_file_id": "ID файла записи",
    "download_url": "Ссылка на запись",
    "audio_path": "Путь к аудио",
    "local_audio_source_used": "Использован локальный источник аудио",
    "local_audio_source_path": "Локальный источник аудио",
    "bitnewton_task_id": "ID задачи Bit.Newton",
    "asr_status": "Статус Bit.Newton ASR",
    "asr_skipped": "ASR пропущена",
    "asr_skipped_calls": "Звонков без новой ASR",
    "attach_result": "Результат прикрепления в Bitrix",
    "timeline_log_result": "Запись анализа в таймлайн",
    "timeline_log_error": "Ошибка записи в таймлайн",
    "error": "Ошибка",
    "calls_count": "Кол-во звонков по сделке",
    "first_response_minutes": "Время до первого звонка, мин.",
    "reaction_speed_label": "Скорость реакции менеджера",
    "first_response_sla_ok": "Первый контакт в срок",
    "first_response_explanation": "Что значит первый контакт",
    "deal_quality_score": "Оценка заполнения сделки",
    "deal_quality_details": "Критерии заполнения сделки",
    "has_contact": "Есть контакт/компания",
    "has_amount": "Указана сумма",
    "has_title": "Есть название",
    "has_comments": "Есть комментарии/следующие шаги",
    "recording_diagnostics": "Диагностика записи",
    "download_attempts": "Попытки REST-скачивания",
    "vibecode_download_used": "Скачано через VibeCode",
    "vibecode_download_error": "Ошибка скачивания VibeCode",
    "ui_download_errors": "Ошибки UI-скачивания",
    "ui_download_used": "Использовано UI-скачивание",
    "ui_download_path": "Путь UI-скачивания",
    "audio_size_bytes": "Размер аудио, байт",
    "transcript_excerpt": "Фрагмент расшифровки",
    "transcript_text": "Полная расшифровка",
    "transcript_marked": "Расшифровка с пометками",
    "transcript_path": "Файл расшифровки",
    "transcript_hash": "Хеш расшифровки",
    "call_quality_score": "Оценка качества разговора",
    "call_quality_details": "Критерии качества разговора",
    "call_checklist_total_score": "Баллы по чек-листу звонка",
    "call_checklist_max_score": "Максимум чек-листа звонка",
    "call_checklist_percent": "Чек-лист звонка, %",
    "call_checklist_block_details": "Оценка этапов продаж",
    "checklist_block_name": "Этап продаж",
    "checklist_criterion": "Критерий чек-листа",
    "checklist_score": "Оценка критерия",
    "checklist_max_score": "Максимум критерия",
    "checklist_evidence": "Доказательство из расшифровки",
    "checklist_comment": "Комментарий оценки",
    "checklist_code": "Код критерия",
    "sales_stage_block_name": "Этап продаж",
    "sales_stage_score": "Баллы этапа",
    "sales_stage_max_score": "Максимум этапа",
    "sales_stage_percent": "Выполнение этапа, %",
    "sales_stage_missing": "Что усилить по этапу",
    "manager_stage_calls": "Звонков с оценкой этапа",
    "manager_stage_deals": "Сделок с оценкой этапа",
    "manager_stage_avg_percent": "Среднее выполнение этапа, %",
    "manager_stage_weak_calls": "Звонков ниже нормы",
    "manager_stage_weak_rate": "Доля слабых звонков, %",
    "criterion_calls": "Звонков с критерием",
    "criterion_avg_score": "Средняя оценка критерия",
    "criterion_completion_percent": "Выполнение критерия, %",
    "criterion_failed_count": "Провалов критерия",
    "criterion_partial_count": "Частично выполнено",
    "criterion_fail_rate": "Доля проблем, %",
    "training_recommendation": "Рекомендация для обучения",
    "top_checklist_gaps": "Главные провалы чек-листа",
    "has_greeting": "Есть приветствие",
    "has_needs_discovery": "Выявлены потребности",
    "has_objection_work": "Есть работа с возражениями",
    "has_next_step_phrase": "Озвучен следующий шаг",
    "alignment_score": "Связь звонка с CRM",
    "crm_work_score": "Оценка ведения CRM",
    "alignment_details": "Что значит связь звонка с CRM",
    "title_mentions": "Совпадения с названием сделки",
    "amount_mentioned": "Сумма упомянута в разговоре",
    "next_step_synced": "Следующий шаг синхронизирован с CRM",
    "next_step_synced_details": "Что дает синхронизация следующего шага",
    "crm_checklist_total_score": "Баллы по CRM-чек-листу",
    "crm_checklist_max_score": "Максимальный балл CRM",
    "crm_checklist_percent": "CRM-чек-лист, %",
    "crm_checklist_details": "Критерии ведения CRM",
    "crm_checklist_block_name": "Блок CRM",
    "crm_checklist_criterion": "Критерий CRM",
    "crm_checklist_score": "Оценка CRM-критерия",
    "crm_checklist_comment": "Комментарий CRM-оценки",
    "crm_checklist_code": "Код CRM-критерия",
    "crm_criterion_deals": "Сделок с критерием",
    "crm_criterion_avg_score": "Средняя оценка CRM-критерия",
    "crm_criterion_completion_percent": "Выполнение CRM-критерия, %",
    "crm_criterion_failed_count": "Провалов CRM-критерия",
    "crm_criterion_partial_count": "Частично выполнено CRM",
    "crm_criterion_fail_rate": "Доля CRM-проблем, %",
    "control_priority": "Приоритет контроля",
    "control_priority_order": "Порядок приоритета",
    "control_reason": "Причина контроля",
    "control_next_action": "Что сделать дальше",
    "quality_control_score": "Оценка риска контроля",
    "training_source": "Источник обучения",
    "training_topic": "Тема обучения",
    "coaching_priority": "Приоритет обучения",
    "coaching_metric": "Метрика провала",
    "coaching_affected_count": "Сколько кейсов затронуто",
    "summary_section": "Раздел",
    "summary_metric": "Показатель",
    "summary_value": "Значение",
    "summary_comment": "Комментарий",
    "manager_rank": "Место",
    "manager_focus": "Фокус руководителя",
    "manager_critical_deals": "Критичных сделок",
    "manager_high_deals": "Высокий приоритет сделок",
    "manager_training_topics": "Тем обучения",
    "manager_top_training_topic": "Главная тема обучения",
    "manager_next_action": "Следующее действие руководителя",
    "overall_score": "Итоговая оценка",
    "overall_score_details": "Из чего складывается итоговая оценка",
    "overall_score_cmp": "Итоговая оценка сравнения",
    "overall_score_delta": "Разница итоговой оценки",
    "call_quality_score_cmp": "Качество разговора сравнение",
    "deal_quality_score_cmp": "Заполнение сделки сравнение",
    "alignment_score_cmp": "Связь звонка с CRM сравнение",
    "call_quality_conclusion": "Вывод по разговору",
    "client_work_conclusion": "Вывод по проработке клиента",
    "improvement_moments": "Моменты для улучшения",
    "objections_count": "Кол-во возражений",
    "unhandled_objections_count": "Кол-во неотработанных возражений",
    "objections_handled": "Возражения отработаны",
    "objections_found": "Найденные возражения",
    "unhandled_objections": "Неотработанные возражения",
    "objection_recommendations": "Варианты отработки возражений",
    "objection_status": "Статус отработки",
    "objection_fragment": "Фрагмент с возражением",
    "recommendations": "Рекомендации",
    "calls_total": "Всего звонков",
    "calls_ok": "Успешно обработано",
    "overall_score_sum": "Сумма итоговых оценок",
    "growth_deal_data": "Зона роста: данные CRM",
    "growth_call_structure": "Зона роста: структура разговора",
    "growth_alignment": "Зона роста: связь с CRM",
    "avg_overall_score": "Средняя итоговая оценка",
    "top_growth_zones": "Главные зоны роста",
    "avg_call_quality_score": "Средняя оценка разговоров",
    "client_work_score": "Оценка проработки клиента",
    "client_work_quality": "Качество проработки клиента",
    "conversation_quality": "Качество разговоров",
    "transcripts_count": "Кол-во расшифровок",
    "transcript_paths": "Файлы расшифровок",
    "no_calls": "Нет звонков по сделке",
    "deals_without_calls": "Сделок без звонков",
    "deals_total": "Всего сделок",
    "calls_failed": "Ошибок по звонкам",
    "ignored_call_center_calls": "Исключено звонков Call-центра",
    "skipped_short_calls": "Исключено коротких звонков",
    "calls_breakdown": "Звонки внутри сделки",
    "transcripts_combined": "Все расшифровки по сделке",
    "bitrix_card_transcript": "Расшифровка из карточки Bitrix",
    "bitrix_card_transcript_status": "Статус расшифровки Bitrix",
    "transcript_match_score": "Совпадение Bit.Newton/Bitrix, %",
    "conversation_meaning": "Смысл разговора",
    "improvement_moments_combined": "Общие моменты для улучшения",
    "objections_combined": "Возражения по сделке",
    "call_number": "Номер звонка в сделке",
    "call_summary": "Кратко по звонку",
    "call_has_error": "Ошибка по звонку",
    "deal_row_type": "Тип строки",
    "lost_deal_url": "Ссылка на проигранную сделку",
    "lost_deal_title": "Название проигранной сделки",
    "lost_stage_name": "Стадия проигрыша",
    "lost_manager_name": "Менеджер",
    "lost_amount": "Сумма потери",
    "lost_date_create": "Дата создания",
    "lost_close_date": "Дата проигрыша",
    "lost_lifetime_days": "Срок жизни сделки, дн.",
    "lost_source": "Источник",
    "lost_analysis_basis": "Основа анализа отказа",
    "loss_reason_category": "Типичная причина отказа",
    "loss_reason_confidence": "Уверенность причины",
    "loss_reason_evidence": "Фрагмент/основание причины",
    "lost_deals_count": "Кол-во проигранных сделок",
    "lost_deals_share": "Доля проигрышей, %",
    "lost_avg_lifetime_days": "Средний срок жизни, дн.",
    "lost_top_managers": "Менеджеры с частыми потерями",
    "conversion_tools": "Инструменты для роста конверсии",
    "conversion_next_action": "Что внедрить дальше",
    "conversion_priority": "Приоритет внедрения",
    "conversion_rank": "Порядок внедрения",
    "conversion_expected_effect": "Ожидаемый эффект",
    "ci_moment_type": "Тип момента",
    "ci_moment_risk": "Риск момента",
    "ci_moment_fragment": "Фрагмент разговора",
    "ci_moment_recommendation": "Что улучшить",
    "ci_moment_source": "Источник вывода",
    "ci_confidence": "Уверенность вывода",
    "objection_type": "Тип возражения",
    "ci_next_manager_action": "Следующее действие менеджера",
    "ci_emotion_state": "Состояние клиента по тексту",
    "ci_emotional_risk_level": "Уровень эмоционального риска",
    "ci_emotional_risk_score": "Оценка эмоционального риска",
    "ci_uncertainty_hits": "Индикаторов сомнения",
    "ci_negative_hits": "Индикаторов негатива/отказа",
    "ci_manager_uncertainty_hits": "Неуверенных формулировок",
    "ci_unhandled_objections_count": "Неотработанных возражений",
    "ci_questions_count": "Вопросов в разговоре",
    "ci_next_step_present": "Следующий шаг прозвучал",
    "ci_risk_evidence": "Основание риска",
    "ci_recommendation": "Рекомендация",
    "ci_conversion_factor": "Фактор конверсии",
    "ci_factor_source": "Источник фактора",
    "ci_factor_priority": "Приоритет фактора",
    "ci_affected_deals": "Затронуто сделок",
    "ci_affected_calls": "Затронуто звонков",
    "ci_factor_share_percent": "Доля затронутых сделок, %",
    "ci_avg_overall_score": "Средняя итоговая оценка",
    "ci_avg_call_quality_score": "Средняя оценка разговора",
    "ci_expected_effect": "Ожидаемый эффект",
    "ci_conversion_action": "Действие для роста конверсии",
    "ci_manager_priority": "Приоритет рекомендации",
    "ci_manager_deals": "Сделок менеджера",
    "ci_manager_calls": "Звонков менеджера",
    "ci_high_risk_calls": "Звонков с высоким риском",
    "ci_no_next_step_count": "Звонков без следующего шага",
    "ci_low_crm_count": "Звонков со слабой CRM",
    "ci_main_growth_area": "Главная зона роста",
    "ci_manager_recommendation": "Рекомендация менеджеру",
    "ci_manager_next_action": "Следующее действие руководителя",
    "script_block": "Блок скрипта",
    "script_step": "Шаг скрипта",
    "script_profile_id": "ID профиля скрипта",
    "script_profile_name": "Профиль скрипта",
    "script_profile_purpose": "Назначение профиля",
    "script_profile_selected": "Профиль выбран для звонка",
    "script_profile_score": "Баллы соответствия скрипту",
    "script_profile_max_score": "Максимум соответствия скрипту",
    "script_profile_match_percent": "Соответствие скрипту, %",
    "script_profile_status": "Статус соответствия скрипту",
    "script_critical_errors_count": "Критичных ошибок",
    "script_critical_errors": "Критичные ошибки",
    "script_failed_steps": "Проваленные шаги",
    "script_profile_recommendation": "Рекомендация по профилю",
    "script_required_action": "Что должен сделать менеджер",
    "script_score": "Оценка по шагу",
    "script_max_score": "Максимум по шагу",
    "script_score_percent": "Выполнение шага, %",
    "script_status": "Статус шага",
    "script_critical_step": "Критичный шаг",
    "script_critical_error": "Критичная ошибка",
    "script_evidence": "Доказательство из расшифровки",
    "script_recommendation": "Рекомендация по шагу",
    "script_weight": "Вес шага",
    "script_gap_count": "Провалов шага",
    "script_partial_count": "Частичных выполнений",
    "script_calls": "Звонков с шагом",
    "script_gap_rate": "Доля проблем, %",
    "script_priority": "Приоритет",
    "script_training_recommendation": "Обучение/действие",
}
